### ISSUE TITLE
Too many entry points

### ISSUE THREAD

**Issue by VaiTon86** [ellenhebert/Grappl#17]
While I was searching in the code, i found a lot of main method, every one with different functions.
The questions are: Why?, Can I assemble them all in a single class and made a maven build?
Sorry for my bad english
Bye

**Comment by ellenhebert** [comment]
They were for testing. There's only one correct entry point, I don't remember where it is though. If you trace the code you should be able to find it.

**Comment by VaiTon86** [comment]
I traced the code and i found that the class Apllication has the mojority of the code, but other classes implements some console arguments.

**Comment by ellenhebert** [comment]
That is the primary way to start Grappl from an IDE.
