### ISSUE TITLE
Can't compile Source

### ISSUE THREAD

**Issue by BenCat07** [ellenhebert/Grappl#23]
I tried Compiling the source, but the main class is missing? Using eclipse, tried to clone directly of Github. Windows 10.

**Comment by ellenhebert** [comment]
build.sh exists now, should compile fine

**Comment by BenCat07** [comment]
Thank you :D

Am 31.12.2016 18:32 schrieb "Ellen Hebert" <notifications@github.com>:

**Comment by ellenhebert** [comment]
You'll probably need the windows subsystem for linux if you want it to build on windows 10, however
