### ISSUE TITLE
Doesn't support UDP servers

### ISSUE THREAD

**Issue by ellenhebert** [ellenhebert/Grappl#6]

**Comment by Porama6400** [comment]
when do you make it support UDP?

**Comment by Cactose** [comment]
it's not going to happen for a while

**Comment by pjrader1** [comment]
Which end is this issue referring to? Does Grappl itself not listen to game servers that use UDP or that Grappl doesn't communicate with its own servers with UDP?

**Comment by Porama6400** [comment]
i mean not support game that server use UDP protocol

**Comment by Cactose** [comment]
The issue is referring to the lack of support for game servers that use UDP. There isn't any need for Grappl itself to use it to communicate with it's own servers.

**Comment by ellenhebert** [comment]
never happening
